trigger:
- main

pool:
  name: Default

steps:

- checkout: self

- powershell: |
    & "C:\Users\JeimySolanyiArguello\Desktop\apache-jmeter-5.6.3\bin\jmeter.bat" -v
  displayName: 'Verificar instalación JMeter'